package com.briup.apps.poll.bean;

import io.swagger.annotations.ApiModelProperty;

public class Survey {
	
	//新创建课调后的状态
		public static final String STATUS_INIT = "未开启";
		//点击开始按钮，意味着当前可以执行课调code
		public static final String STATUS_BEGIN = "开启";
		//点击关闭按钮，意味着关闭课调code
		public static final String STATUS_CHECK_UN = "未审核";
		public static final String STATUS_CHECK_PASS = "审核成功";

		public static final String STATUS_CHECK_NOPASS = "未审核成功";
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survey.id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
	@ApiModelProperty(value="主键  自增")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survey.average
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
	@ApiModelProperty(value="课调平均分")
    private Double average;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survey.status
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    @ApiModelProperty(value="课调状态")
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survey.code
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    @ApiModelProperty(value="课调编码")
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survey.surveyDate
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    @ApiModelProperty(value="课调时间")
    private String surveydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survey.course_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    @ApiModelProperty(value="课程id")
    private Long courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survey.clazz_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    @ApiModelProperty(value="班级id")
    private Long clazzId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survey.user_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    @ApiModelProperty(value="用户id")
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survey.questionnaire_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    @ApiModelProperty(value="问卷id")
    private Long questionnaireId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survey.id
     *
     * @return the value of poll_survey.id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survey.id
     *
     * @param id the value for poll_survey.id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survey.average
     *
     * @return the value of poll_survey.average
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public Double getAverage() {
        return average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survey.average
     *
     * @param average the value for poll_survey.average
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public void setAverage(Double average) {
        this.average = average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survey.status
     *
     * @return the value of poll_survey.status
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survey.status
     *
     * @param status the value for poll_survey.status
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survey.code
     *
     * @return the value of poll_survey.code
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survey.code
     *
     * @param code the value for poll_survey.code
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survey.surveyDate
     *
     * @return the value of poll_survey.surveyDate
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public String getSurveydate() {
        return surveydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survey.surveyDate
     *
     * @param surveydate the value for poll_survey.surveyDate
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public void setSurveydate(String surveydate) {
        this.surveydate = surveydate == null ? null : surveydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survey.course_id
     *
     * @return the value of poll_survey.course_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survey.course_id
     *
     * @param courseId the value for poll_survey.course_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survey.clazz_id
     *
     * @return the value of poll_survey.clazz_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public Long getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survey.clazz_id
     *
     * @param clazzId the value for poll_survey.clazz_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public void setClazzId(Long clazzId) {
        this.clazzId = clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survey.user_id
     *
     * @return the value of poll_survey.user_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survey.user_id
     *
     * @param userId the value for poll_survey.user_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survey.questionnaire_id
     *
     * @return the value of poll_survey.questionnaire_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public Long getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survey.questionnaire_id
     *
     * @param questionnaireId the value for poll_survey.questionnaire_id
     *
     * @mbg.generated Tue Jul 03 09:12:36 CST 2018
     */
    public void setQuestionnaireId(Long questionnaireId) {
        this.questionnaireId = questionnaireId;
    }
}